// src/components/mathSymbols.js
const mathSymbols = {
  Basic: [
    { symbol: "☐^2", latex: "{}^{2}", moveLeft: 4 },
    { symbol: "☐^☐", latex: "{}^{}", moveLeft: 0 },
    { symbol: "\\sqrt{☐}", latex: "\\sqrt{}", moveLeft: 1 },
    { symbol: "\\sqrt[☐]{☐}", latex: "\\sqrt[]{}", moveLeft: 3 },
    { symbol: "\\frac{☐}{☐}", latex: "\\frac{}{}", moveLeft: 3 },
    { symbol: "log_☐", latex: "\\log_{}", moveLeft: 1 },
    { symbol: "π", latex: "\\pi", moveLeft: 0 },
    { symbol: "θ", latex: "\\theta", moveLeft: 0 },
    { symbol: "∞", latex: "\\infty", moveLeft: 0 },
    { symbol: "∫", latex: "\\int", moveLeft: 0 },
    { symbol: "\\frac{d}{dx}", latex: "\\frac{d}{dx}", moveLeft: 0 },
    { symbol: "≥", latex: "\\geq", moveLeft: 0 },
    { symbol: "≤", latex: "\\leq", moveLeft: 0 },
    { symbol: "·", latex: "\\cdot", moveLeft: 0 },
    { symbol: "÷", latex: "\\div", moveLeft: 0 },
    { symbol: "☐^°", latex: "{}^\\circ", moveLeft: 8 },
    { symbol: "\\left(☐\\right)", latex: "\\left({}\\right)", moveLeft: 8 },
    { symbol: "|☐|", latex: "\\left|{}\\right|", moveLeft: 8 },
    { symbol: "f∘g", latex: "(f \\circ g)", moveLeft: 0 },
    { symbol: "f(x)", latex: "f(x)", moveLeft: 0 },
    { symbol: "ln", latex: "\\ln", moveLeft: 0 },
    { symbol: "e^☐", latex: "e^{}", moveLeft: 1 },
    {
      symbol: "\\frac{\\partial}{\\partial x}",
      latex: "\\frac{\\partial}{\\partial x}",
      moveLeft: 0,
    },
    {
      symbol: "\\int_{☐}^{☐}",
      latex: "\\int_{}^{}",
      moveLeft: 4,
    },
    {
      symbol: "\\lim",
      latex: "\\lim",
      moveLeft: 0,
    },
    {
      symbol: "\\sum",
      latex: "\\sum",
      moveLeft: 0,
    },
    { symbol: "sin", latex: "\\sin \\left(\\right)", moveLeft: 1 },
    { symbol: "cos", latex: "\\cos \\left(\\right)", moveLeft: 1 },
    { symbol: "tan", latex: "\\tan \\left(\\right)", moveLeft: 1 },
    { symbol: "cot", latex: "\\cot \\left(\\right)", moveLeft: 1 },
    // Thêm các biểu thức từ dữ liệu đầu vào
    { symbol: "x^2", latex: "x^{2}", moveLeft: 0 }, // Từ câu hỏi về đạo hàm của \(x^2\)
    { symbol: "\\sqrt{x}", latex: "\\sqrt{x}", moveLeft: 0 }, // Từ câu hỏi về \(\sqrt{x}\)
    { symbol: "\\sqrt[3]{x}", latex: "\\sqrt[3]{x}", moveLeft: 0 }, // Từ câu hỏi về \(\sqrt[3]{x}\)
    { symbol: "f'(x)", latex: "f'(x)", moveLeft: 0 }, // Đạo hàm \(f'(x)\)
  ],

  "Greek (small)": [
    { symbol: "α", latex: "\\alpha", moveLeft: 0 },
    { symbol: "β", latex: "\\beta", moveLeft: 0 },
    { symbol: "γ", latex: "\\gamma", moveLeft: 0 },
    { symbol: "δ", latex: "\\delta", moveLeft: 0 },
    { symbol: "\\varphi", latex: "\\varphi", moveLeft: 0 },
    { symbol: "ζ", latex: "\\zeta", moveLeft: 0 },
    { symbol: "η", latex: "\\eta", moveLeft: 0 },
    { symbol: "θ", latex: "\\theta", moveLeft: 0 },
    { symbol: "ι", latex: "\\iota", moveLeft: 0 },
    { symbol: "κ", latex: "\\kappa", moveLeft: 0 },
    { symbol: "λ", latex: "\\lambda", moveLeft: 0 },
    { symbol: "μ", latex: "\\mu", moveLeft: 0 },
    { symbol: "ν", latex: "\\nu", moveLeft: 0 },
    { symbol: "ξ", latex: "\\xi", moveLeft: 0 },
    { symbol: "π", latex: "\\pi", moveLeft: 0 },
    { symbol: "ρ", latex: "\\rho", moveLeft: 0 },
    { symbol: "σ", latex: "\\sigma", moveLeft: 0 },
    { symbol: "τ", latex: "\\tau", moveLeft: 0 },
    { symbol: "υ", latex: "\\upsilon", moveLeft: 0 },
    { symbol: "ϕ", latex: "\\phi", moveLeft: 0 },
    { symbol: "χ", latex: "\\chi", moveLeft: 0 },
    { symbol: "ψ", latex: "\\psi", moveLeft: 0 },
    { symbol: "ω", latex: "\\omega", moveLeft: 0 },
    { symbol: "ε", latex: "\\varepsilon", moveLeft: 0 },
    { symbol: "ϑ", latex: "\\vartheta", moveLeft: 0 },
    { symbol: "H", latex: "\\mathcal{H}", moveLeft: 0 },
    { symbol: "ϖ", latex: "\\varpi", moveLeft: 0 },
    { symbol: "ϱ", latex: "\\varrho", moveLeft: 0 },
    { symbol: "o", latex: "\\omicron", moveLeft: 0 },
    { symbol: "δ", latex: "\\delta", moveLeft: 0 },
    { symbol: "ϵ", latex: "\\epsilon", moveLeft: 0 },
  ],

  "Greek (large)": [
    { symbol: "\\Alpha", latex: "\\Alpha", moveLeft: 0 },
    { symbol: "\\Beta", latex: "\\Beta", moveLeft: 0 },
    { symbol: "\\Gamma", latex: "\\Gamma", moveLeft: 0 },
    { symbol: "\\Delta", latex: "\\Delta", moveLeft: 0 },
    { symbol: "\\Phi", latex: "\\Phi", moveLeft: 0 },
    { symbol: "\\Zeta", latex: "\\Zeta", moveLeft: 0 },
    { symbol: "\\Eta", latex: "\\Eta", moveLeft: 0 },
    { symbol: "\\Theta", latex: "\\Theta", moveLeft: 0 },
    { symbol: "\\Iota", latex: "\\Iota", moveLeft: 0 },
    { symbol: "\\Kappa", latex: "\\Kappa", moveLeft: 0 },
    { symbol: "\\Lambda", latex: "\\Lambda", moveLeft: 0 },
    { symbol: "\\Mu", latex: "\\Mu", moveLeft: 0 },
    { symbol: "\\Nu", latex: "\\Nu", moveLeft: 0 },
    { symbol: "\\Xi", latex: "\\Xi", moveLeft: 0 },
    { symbol: "\\Pi", latex: "\\Pi", moveLeft: 0 },
    { symbol: "\\Rho", latex: "\\Rho", moveLeft: 0 },
    { symbol: "\\Sigma", latex: "\\Sigma", moveLeft: 0 },
    { symbol: "\\Tau", latex: "\\Tau", moveLeft: 0 },
    { symbol: "\\Upsilon", latex: "\\Upsilon", moveLeft: 0 },
    { symbol: "\\Phi", latex: "\\Phi", moveLeft: 0 },
    { symbol: "\\Chi", latex: "\\Chi", moveLeft: 0 },
    { symbol: "\\Psi", latex: "\\Psi", moveLeft: 0 },
    { symbol: "\\Omega", latex: "\\Omega", moveLeft: 0 },
    { symbol: "\\Theta", latex: "\\Theta", moveLeft: 0 },
    { symbol: "\\mathscr{H}", latex: "\\mathscr{H}", moveLeft: 0 },
    { symbol: "\\Rho", latex: "\\Rho", moveLeft: 0 },
    { symbol: "\\Omicron", latex: "\\Omicron", moveLeft: 0 },
    { symbol: "\\Delta", latex: "\\Delta", moveLeft: 0 },
    { symbol: "\\Epsilon", latex: "\\Epsilon", moveLeft: 0 },
  ],

  Trigonometry: [
    { symbol: "sin", latex: "\\sin \\left(\\right)", moveLeft: 1 },
    { symbol: "cos", latex: "\\cos \\left(\\right)", moveLeft: 1 },
    { symbol: "tan", latex: "\\tan \\left(\\right)", moveLeft: 1 },
    { symbol: "cot", latex: "\\cot \\left(\\right)", moveLeft: 1 },
    { symbol: "sec", latex: "\\sec \\left(\\right)", moveLeft: 1 },
    { symbol: "csc", latex: "\\csc \\left(\\right)", moveLeft: 1 },
    { symbol: "sinh", latex: "\\sinh \\left(\\right)", moveLeft: 1 },
    { symbol: "cosh", latex: "\\cosh \\left(\\right)", moveLeft: 1 },
    { symbol: "tanh", latex: "\\tanh \\left(\\right)", moveLeft: 1 },
    { symbol: "arcsin", latex: "\\arcsin \\left(\\right)", moveLeft: 1 },
    { symbol: "arccos", latex: "\\arccos \\left(\\right)", moveLeft: 1 },
    { symbol: "arctan", latex: "\\arctan \\left(\\right)", moveLeft: 1 },
    { symbol: "arccot", latex: "\\text{arccot} \\left(\\right)", moveLeft: 1 },
    { symbol: "arcsec", latex: "\\text{arcsec} \\left(\\right)", moveLeft: 1 },
    { symbol: "arccsc", latex: "\\text{arccsc} \\left(\\right)", moveLeft: 1 },
    { symbol: "coth", latex: "\\coth \\left(\\right)", moveLeft: 1 },
    { symbol: "sech", latex: "\\text{sech} \\left(\\right)", moveLeft: 1 },
    { symbol: "csch", latex: "\\text{csch} \\left(\\right)", moveLeft: 1 },
    { symbol: "arsinh", latex: "\\text{arsinh} \\left(\\right)", moveLeft: 1 },
    { symbol: "arcosh", latex: "\\text{arcosh} \\left(\\right)", moveLeft: 1 },
    { symbol: "artanh", latex: "\\text{artanh} \\left(\\right)", moveLeft: 1 },
    { symbol: "arcoth", latex: "\\text{arcoth} \\left(\\right)", moveLeft: 1 },
    { symbol: "arsech", latex: "\\text{arsech} \\left(\\right)", moveLeft: 1 },
    { symbol: "arcsch", latex: "\\text{arcsch} \\left(\\right)", moveLeft: 1 },
    { symbol: "sin²", latex: "\\sin^{2} \\left(\\right)", moveLeft: 1 },
    { symbol: "cos²", latex: "\\cos^{2} \\left(\\right)", moveLeft: 1 },
    { symbol: "tan²", latex: "\\tan^{2} \\left(\\right)", moveLeft: 1 },
    { symbol: "cot²", latex: "\\cot^{2} \\left(\\right)", moveLeft: 1 },
    { symbol: "sec²", latex: "\\sec^{2} \\left(\\right)", moveLeft: 1 },
    { symbol: "csc²", latex: "\\csc^{2} \\left(\\right)", moveLeft: 1 },
    // Thêm từ dữ liệu đầu vào
    { symbol: "\\tan \\alpha", latex: "\\tan \\alpha", moveLeft: 0 }, // Từ câu hỏi về \(\tan \alpha\)
  ],

  Operators: [
    { symbol: "☐^2", latex: "{}^{2}", moveLeft: 4 },
    { symbol: "☐^☐", latex: "{}^{}", moveLeft: 0 },
    { symbol: "\\sqrt{☐}", latex: "\\sqrt{}", moveLeft: 1 },
    { symbol: "\\sqrt[☐]{☐}", latex: "\\sqrt[]{}", moveLeft: 3 },
    { symbol: "\\frac{☐}{☐}", latex: "\\frac{}{}", moveLeft: 3 },
    { symbol: "log_☐", latex: "\\log_{}", moveLeft: 1 },
    { symbol: "π", latex: "\\pi", moveLeft: 0 },
    { symbol: "θ", latex: "\\theta", moveLeft: 0 },
    { symbol: "∞", latex: "\\infty", moveLeft: 0 },
    { symbol: "∫", latex: "\\int", moveLeft: 0 },
    { symbol: "\\frac{d}{dx}", latex: "\\frac{d}{dx}", moveLeft: 0 },
    { symbol: "!", latex: "!", moveLeft: 0 },
    { symbol: "=", latex: "=", moveLeft: 0 },
    { symbol: "≈", latex: "\\approx", moveLeft: 0 },
    { symbol: "≠", latex: "\\ne", moveLeft: 0 },
    { symbol: "÷", latex: "\\div", moveLeft: 0 },
    { symbol: "·", latex: "\\cdot", moveLeft: 0 },
    { symbol: "×", latex: "\\times", moveLeft: 0 },
    { symbol: "<", latex: "<", moveLeft: 0 },
    { symbol: ">", latex: ">", moveLeft: 0 },
    { symbol: "≤", latex: "\\leq", moveLeft: 0 },
    { symbol: "≥", latex: "\\geq", moveLeft: 0 },
    { symbol: "(☐)", latex: "()", moveLeft: 0 },
    { symbol: "[☐]", latex: "[]", moveLeft: 0 },
    { symbol: "e^☐", latex: "e^{}", moveLeft: 1 },
    {
      symbol: "\\lfloor {☐} \\rfloor",
      latex: "\\lfloor {} \\rfloor",
      moveLeft: 0,
    },
    { symbol: "\\lceil {☐} \\rceil", latex: "\\lceil {} \\rceil", moveLeft: 0 },
    { symbol: "\\rightarrow", latex: "\\rightarrow", moveLeft: 0 },
    { symbol: "☐^\\circ", latex: "\\geq", moveLeft: 0 },
    // Thêm từ dữ liệu đầu vào
    { symbol: "\\Delta x", latex: "\\Delta x", moveLeft: 0 }, // Số gia \(\Delta x\)
    { symbol: "\\Delta y", latex: "\\Delta y", moveLeft: 0 }, // Số gia \(\Delta y\)
    { symbol: "o(\\Delta x)", latex: "o(\\Delta x)", moveLeft: 0 }, // Đại lượng vô cùng bé bậc cao
  ],

  Accents: [
    { symbol: "\\overline{x}", latex: "\\overline{ }", moveLeft: 1 },
    { symbol: "\\vec{x}", latex: "\\vec{ }", moveLeft: 1 },
    { symbol: "∈", latex: "\\in", moveLeft: 0 },
    { symbol: "∀", latex: "\\forall", moveLeft: 0 },
    { symbol: "∉", latex: "\\notin", moveLeft: 0 },
    { symbol: "∃", latex: "\\exists", moveLeft: 0 },
    { symbol: "ℝ", latex: "\\mathbb{R}", moveLeft: 0 },
    { symbol: "ℂ", latex: "\\mathbb{C}", moveLeft: 0 },
    { symbol: "ℕ", latex: "\\mathbb{N}", moveLeft: 0 },
    { symbol: "ℤ", latex: "\\mathbb{Z}", moveLeft: 0 },
    { symbol: "∅", latex: "\\emptyset", moveLeft: 0 },
    { symbol: "∨", latex: "\\lor", moveLeft: 0 },
    { symbol: "∧", latex: "\\land", moveLeft: 0 },
    { symbol: "¬", latex: "\\neg", moveLeft: 0 },
    { symbol: "⊕", latex: "\\oplus", moveLeft: 0 },
    { symbol: "∩", latex: "\\cap", moveLeft: 0 },
    { symbol: "∪", latex: "\\cup", moveLeft: 0 },
    { symbol: "\\subset", latex: "\\subset", moveLeft: 0 },
    { symbol: "\\subseteq", latex: "\\subseteq", moveLeft: 0 },
    { symbol: "\\supset", latex: "\\supset", moveLeft: 0 },
    { symbol: "\\supseteq", latex: "\\supseteq", moveLeft: 0 },
    { symbol: "x^c", latex: "^c", moveLeft: 0 },
    { symbol: "\\hat{x}", latex: "\\hat{ }", moveLeft: 1 },
    { symbol: "\\tilde{x}", latex: "\\tilde{ }", moveLeft: 1 },
    { symbol: "\\not\\subset", latex: "\\not\\subset", moveLeft: 0 },
    { symbol: "\\not\\subseteq", latex: "\\not\\subseteq", moveLeft: 0 },
    { symbol: "\\mathbb{Q}", latex: "\\mathbb{Q}", moveLeft: 0 },
    { symbol: "\\implies", latex: "\\implies", moveLeft: 0 },
    { symbol: "\\iff", latex: "\\iff", moveLeft: 0 },
    { symbol: "\\perp", latex: "\\perp", moveLeft: 0 },
  ],

  "Big Operators": [
    { symbol: "☐^2", latex: "{}^{2}", moveLeft: 4 },
    { symbol: "☐^☐", latex: "{}^{}", moveLeft: 0 },
    { symbol: "\\sqrt{☐}", latex: "\\sqrt{}", moveLeft: 1 },
    { symbol: "\\sqrt[☐]{☐}", latex: "\\sqrt[]{}", moveLeft: 3 },
    { symbol: "\\frac{☐}{☐}", latex: "\\frac{}{}", moveLeft: 3 },
    { symbol: "log_☐", latex: "\\log_{}", moveLeft: 1 },
    { symbol: "π", latex: "\\pi", moveLeft: 0 },
    { symbol: "e^☐", latex: "e^{}", moveLeft: 1 },
    { symbol: "θ", latex: "\\theta", moveLeft: 0 },
    { symbol: "∞", latex: "\\infty", moveLeft: 0 },
    { symbol: "∫", latex: "\\int", moveLeft: 0 },
    { symbol: "∫∫", latex: "\\int \\int", moveLeft: 0 },
    { symbol: "∫∫∫", latex: "\\int \\int \\int", moveLeft: 0 },
    { symbol: "\\int_{☐}^{☐}", latex: "\\int_{}^{}", moveLeft: 4 },
    {
      symbol: "\\int_{☐}^{☐}\\int_{☐}^{☐}",
      latex: "\\int_{}^{}\\int_{}^{}",
      moveLeft: 4,
    },
    {
      symbol: "\\int_{☐}^{☐}\\int_{☐}^{☐}\\int_{☐}^{☐}",
      latex: "\\int_{}^{}\\int_{}^{}\\int_{}^{}",
      moveLeft: 4,
    },
    { symbol: "\\oint", latex: "\\oint", moveLeft: 0 },
    { symbol: "\\oint \\oint", latex: "\\oint \\oint", moveLeft: 0 },
    {
      symbol: "\\oint \\oint \\oint",
      latex: "\\oint \\oint \\oint",
      moveLeft: 0,
    },
    { symbol: "\\oint_{☐}^{☐}", latex: "\\oint_{}^{}", moveLeft: 4 },
    {
      symbol: "\\oint_{☐}^{☐}\\oint_{☐}^{☐}",
      latex: "\\int_{}^{}\\int_{}^{}",
      moveLeft: 4,
    },
    {
      symbol: "\\oint_{☐}^{☐}\\oint_{☐}^{☐}\\oint_{☐}^{☐}",
      latex: "\\int_{}^{}\\int_{}^{}\\int_{}^{}",
      moveLeft: 4,
    },
    {
      symbol: "\\sum_{n=0}^{\\infty}",
      latex: "\\sum_{n=0}^{\\infty}",
      moveLeft: 1,
    },
    {
      symbol: "\\prod_{n=0}^{\\infty}",
      latex: "\\prod_{n=0}^{\\infty}",
      moveLeft: 1,
    },
    { symbol: "\\frac{d}{dx}", latex: "\\frac{d}{dx}", moveLeft: 1 },
    { symbol: "\\frac{d^2}{dx^2}", latex: "\\frac{d^2}{dx^2}", moveLeft: 1 },
    { symbol: "(□)'", latex: "(\\{})'", moveLeft: 1 },
    { symbol: "(□)''", latex: "(\\{})''", moveLeft: 1 },
    {
      symbol: "\\frac{\\partial}{\\partial x}",
      latex: "\\frac{\\partial}{\\partial x}",
      moveLeft: 1,
    },
    {
      symbol: "\\frac{\\partial^2}{\\partial {x}{y}}",
      latex: "\\frac{\\partial^2}{\\partial {x}{y}}",
      moveLeft: 1,
    },
    {
      symbol: "\\lim_{x\\to☐}",
      latex: "\\lim_{x\\to{}}",
      moveLeft: 3,
    },
    {
      symbol: "\\lim_{x\\to{\\infty}}",
      latex: "\\lim_{x\\to{\\infty}}",
      moveLeft: 3,
    },
    {
      symbol: "\\lim_{x\\to{☐^+}}",
      latex: "\\lim_{x\\to{^{+}}}",
      moveLeft: 3,
    },
    {
      symbol: "\\lim_{x\\to{☐^-}}",
      latex: "\\lim_{x\\to{^{-}}}",
      moveLeft: 3,
    },
    // Thêm từ dữ liệu đầu vào
    {
      symbol: "\\lim_{x \\to x_0} \\frac{f(x) - f(x_0)}{x - x_0}",
      latex: "\\lim_{x \\to x_0} \\frac{f(x) - f(x_0)}{x - x_0}",
      moveLeft: 0,
    }, // Định nghĩa đạo hàm
    {
      symbol: "\\lim_{h \\to 0} \\frac{f(x+h) - f(x)}{h}",
      latex: "\\lim_{h \\to 0} \\frac{f(x+h) - f(x)}{h}",
      moveLeft: 0,
    }, // Định nghĩa đạo hàm khác
    {
      symbol: "\\lim_{\\Delta x \\to 0} \\frac{f(x + \\Delta x) - f(x)}{\\Delta x}",
      latex: "\\lim_{\\Delta x \\to 0} \\frac{f(x + \\Delta x) - f(x)}{\\Delta x}",
      moveLeft: 0,
    }, // Định nghĩa đạo hàm với \(\Delta x\)
    {
      symbol: "\\frac{dy}{dx}",
      latex: "\\frac{dy}{dx}",
      moveLeft: 0,
    }, // Ký hiệu đạo hàm \(\frac{dy}{dx}\)
    {
      symbol: "\\frac{f(x+h) - f(x)}{h}",
      latex: "\\frac{f(x+h) - f(x)}{h}",
      moveLeft: 0,
    }, // Thương sai
    {
      symbol: "\\frac{f(x) - f(x_0)}{x - x_0}",
      latex: "\\frac{f(x) - f(x_0)}{x - x_0}",
      moveLeft: 0,
    }, // Thương sai khác
  ],

  "Matrices & Vectors": [
    {
      symbol: "2×2",
      latex: "\\begin{pmatrix} \\Box & \\Box \\\\ \\Box & \\Box \\end{pmatrix}",
      moveLeft: 0,
    },
    {
      symbol: "2×3",
      latex:
        "\\begin{pmatrix} \\Box & \\Box & \\Box \\\\ \\Box & \\Box & \\Box \\end{pmatrix}",
      moveLeft: 0,
    },
    {
      symbol: "3×3",
      latex:
        "\\begin{pmatrix} \\Box & \\Box & \\Box \\\\ \\Box & \\Box & \\Box \\\\ \\Box & \\Box & \\Box \\end{pmatrix}",
      moveLeft: 0,
    },
    {
      symbol: "3×2",
      latex:
        "\\begin{pmatrix} \\Box & \\Box \\\\ \\Box & \\Box \\\\ \\Box & \\Box \\end{pmatrix}",
      moveLeft: 0,
    },
    {
      symbol: "4×4",
      latex:
        "\\begin{pmatrix} \\Box & \\Box & \\Box & \\Box \\\\ \\Box & \\Box & \\Box & \\Box \\\\ \\Box & \\Box & \\Box & \\Box \\\\ \\Box & \\Box & \\Box & \\Box \\end{pmatrix}",
      moveLeft: 0,
    },
    {
      symbol: "Custom",
      latex: "custom",
      moveLeft: 0,
      isCustom: true,
    },
  ],

  Chemistry: [
    { symbol: "H₂O", latex: "H_{2}O", moveLeft: 0 },
    { symbol: "CO₂", latex: "CO_{2}", moveLeft: 0 },
    { symbol: "CH₄", latex: "CH_{4}", moveLeft: 0 },
    { symbol: "→", latex: "\\rightarrow", moveLeft: 0 },
    { symbol: "⇌", latex: "\\leftrightharpoons", moveLeft: 0 },
    { symbol: "O₂", latex: "O_{2}", moveLeft: 0 },
    { symbol: "N₂", latex: "N_{2}", moveLeft: 0 },
    { symbol: "H₂", latex: "H_{2}", moveLeft: 0 },
    { symbol: "NH₃", latex: "NH_{3}", moveLeft: 0 },
    { symbol: "HCl", latex: "HCl", moveLeft: 0 },
    { symbol: "NaCl", latex: "NaCl", moveLeft: 0 },
    { symbol: "H₂SO₄", latex: "H_{2}SO_{4}", moveLeft: 0 },
    { symbol: "HNO₃", latex: "HNO_{3}", moveLeft: 0 },
    { symbol: "NaOH", latex: "NaOH", moveLeft: 0 },
    { symbol: "KOH", latex: "KOH", moveLeft: 0 },
    { symbol: "CaCO₃", latex: "CaCO_{3}", moveLeft: 0 },
    { symbol: "MgO", latex: "MgO", moveLeft: 0 },
    { symbol: "Fe₂O₃", latex: "Fe_{2}O_{3}", moveLeft: 0 },
    { symbol: "Al₂O₃", latex: "Al_{2}O_{3}", moveLeft: 0 },
    { symbol: "SO₂", latex: "SO_{2}", moveLeft: 0 },
    { symbol: "SO₃", latex: "SO_{3}", moveLeft: 0 },
    { symbol: "C₂H₅OH", latex: "C_{2}H_{5}OH", moveLeft: 0 },
    { symbol: "CH₃COOH", latex: "CH_{3}COOH", moveLeft: 0 },
    { symbol: "C₆H₁₂O₆", latex: "C_{6}H_{12}O_{6}", moveLeft: 0 },
    { symbol: "C₂H₂", latex: "C_{2}H_{2}", moveLeft: 0 },
    { symbol: "C₂H₄", latex: "C_{2}H_{4}", moveLeft: 0 },
    { symbol: "C₃H₈", latex: "C_{3}H_{8}", moveLeft: 0 },
    { symbol: "H₃PO₄", latex: "H_{3}PO_{4}", moveLeft: 0 },
    { symbol: "K₂CO₃", latex: "K_{2}CO_{3}", moveLeft: 0 },
    { symbol: "Na₂SO₄", latex: "Na_{2}SO_{4}", moveLeft: 0 },
    { symbol: "Ca(OH)₂", latex: "Ca(OH)_{2}", moveLeft: 0 },
    { symbol: "FeCl₃", latex: "FeCl_{3}", moveLeft: 0 },
    { symbol: "CuSO₄", latex: "CuSO_{4}", moveLeft: 0 },
    { symbol: "AgNO₃", latex: "AgNO_{3}", moveLeft: 0 },
    { symbol: "ZnO", latex: "ZnO", moveLeft: 0 },
    { symbol: "BaCl₂", latex: "BaCl_{2}", moveLeft: 0 },
    { symbol: "⇐", latex: "\\leftarrow", moveLeft: 0 },
    { symbol: "⇄", latex: "\\leftrightarrow", moveLeft: 0 },
    { symbol: "↑", latex: "\\uparrow", moveLeft: 0 },
    { symbol: "↓", latex: "\\downarrow", moveLeft: 0 },
  ],

  Calculator: [
    { symbol: "0", latex: "0", moveLeft: 0 },
    { symbol: "1", latex: "1", moveLeft: 0 },
    { symbol: "2", latex: "2", moveLeft: 0 },
    { symbol: "3", latex: "3", moveLeft: 0 },
    { symbol: "4", latex: "4", moveLeft: 0 },
    { symbol: "5", latex: "5", moveLeft: 0 },
    { symbol: "6", latex: "6", moveLeft: 0 },
    { symbol: "7", latex: "7", moveLeft: 0 },
    { symbol: "8", latex: "8", moveLeft: 0 },
    { symbol: "9", latex: "9", moveLeft: 0 },
    { symbol: ".", latex: ".", moveLeft: 0 },
    { symbol: "+", latex: "+", moveLeft: 0 },
    { symbol: "−", latex: "-", moveLeft: 0 },
    { symbol: "×", latex: "\\times", moveLeft: 0 },
    { symbol: "÷", latex: "\\div", moveLeft: 0 },
    { symbol: "sin", latex: "\\sin\\left(\\right)", moveLeft: 1 },
    { symbol: "cos", latex: "\\cos\\left(\\right)", moveLeft: 1 },
    { symbol: "tan", latex: "\\tan\\left(\\right)", moveLeft: 1 },
    { symbol: "sin⁻¹", latex: "\\arcsin\\left(\\right)", moveLeft: 1 },
    { symbol: "cos⁻¹", latex: "\\arccos\\left(\\right)", moveLeft: 1 },
    { symbol: "tan⁻¹", latex: "\\arctan\\left(\\right)", moveLeft: 1 },
    { symbol: "ln", latex: "\\ln\\left(\\right)", moveLeft: 1 },
    { symbol: "log", latex: "\\log\\left(\\right)", moveLeft: 1 },
    { symbol: "√", latex: "\\sqrt{}", moveLeft: 1 },
    { symbol: "x²", latex: "^{2}", moveLeft: 1 },
    { symbol: "x³", latex: "^{3}", moveLeft: 1 },
    { symbol: "xⁿ", latex: "^{}", moveLeft: 1 },
    { symbol: "\\int_{}^{}", latex: "\\int_{}^{}", moveLeft: 3 },
    { symbol: "∑", latex: "\\sum_{}^{}", moveLeft: 3 },
    { symbol: "∏", latex: "\\prod_{}^{}", moveLeft: 3 },
    { symbol: "e", latex: "e", moveLeft: 0 },
    { symbol: "π", latex: "\\pi", moveLeft: 0 },
    { symbol: "∞", latex: "\\infty", moveLeft: 0 },
    { symbol: "=", latex: "=", moveLeft: 0 },
    { symbol: "≠", latex: "\\neq", moveLeft: 0 },
    { symbol: "≤", latex: "\\leq", moveLeft: 0 },
    { symbol: "≥", latex: "\\geq", moveLeft: 0 },
    { symbol: "≈", latex: "\\approx", moveLeft: 0 },
    { symbol: "∀", latex: "\\forall", moveLeft: 0 },
    { symbol: "∃", latex: "\\exists", moveLeft: 0 },
    { symbol: "∈", latex: "\\in", moveLeft: 0 },
    { symbol: "(", latex: "\\left(", moveLeft: 0 },
    { symbol: ")", latex: "\\right)", moveLeft: 0 },
    { symbol: "|x|", latex: "\\left|x\\right|", moveLeft: 1 },
    { symbol: "!", latex: "!", moveLeft: 0 },
  ],
};

export default mathSymbols;